// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WasmorphApiKey struct {
	ID        int32            `json:"id"`
	ApiKey    string           `json:"api_key"`
	UserID    int32            `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	IsActive  pgtype.Bool      `json:"is_active"`
}

type WasmorphRule struct {
	ID         int32            `json:"id"`
	Name       string           `json:"name"`
	UserID     int32            `json:"user_id"`
	SourceCode string           `json:"source_code"`
	WasmBinary []byte           `json:"wasm_binary"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	IsActive   pgtype.Bool      `json:"is_active"`
}

type WasmorphUser struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	IsActive     pgtype.Bool      `json:"is_active"`
}
